// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=handler_mocks_test.go -package=http_test
//

// Package http_test is a generated GoMock package.
package http_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/partyzanex/padmark/internal/domain"
	auth "github.com/partyzanex/padmark/internal/usecases/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionManager is a mock of SessionManager interface.
type MockSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerMockRecorder
	isgomock struct{}
}

// MockSessionManagerMockRecorder is the mock recorder for MockSessionManager.
type MockSessionManagerMockRecorder struct {
	mock *MockSessionManager
}

// NewMockSessionManager creates a new mock instance.
func NewMockSessionManager(ctrl *gomock.Controller) *MockSessionManager {
	mock := &MockSessionManager{ctrl: ctrl}
	mock.recorder = &MockSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManager) EXPECT() *MockSessionManagerMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockSessionManager) ChangePassword(ctx context.Context, sessionID, oldPassword, newPassword, totpCode string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, sessionID, oldPassword, newPassword, totpCode)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockSessionManagerMockRecorder) ChangePassword(ctx, sessionID, oldPassword, newPassword, totpCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockSessionManager)(nil).ChangePassword), ctx, sessionID, oldPassword, newPassword, totpCode)
}

// GetSession mocks base method.
func (m *MockSessionManager) GetSession(ctx context.Context, sessionID string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, sessionID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionManagerMockRecorder) GetSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionManager)(nil).GetSession), ctx, sessionID)
}

// Login mocks base method.
func (m *MockSessionManager) Login(ctx context.Context, username, password, totpCode, userAgent, clientIP string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, username, password, totpCode, userAgent, clientIP)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockSessionManagerMockRecorder) Login(ctx, username, password, totpCode, userAgent, clientIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockSessionManager)(nil).Login), ctx, username, password, totpCode, userAgent, clientIP)
}

// Logout mocks base method.
func (m *MockSessionManager) Logout(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockSessionManagerMockRecorder) Logout(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockSessionManager)(nil).Logout), ctx, sessionID)
}

// MockOnboardingManager is a mock of OnboardingManager interface.
type MockOnboardingManager struct {
	ctrl     *gomock.Controller
	recorder *MockOnboardingManagerMockRecorder
	isgomock struct{}
}

// MockOnboardingManagerMockRecorder is the mock recorder for MockOnboardingManager.
type MockOnboardingManagerMockRecorder struct {
	mock *MockOnboardingManager
}

// NewMockOnboardingManager creates a new mock instance.
func NewMockOnboardingManager(ctrl *gomock.Controller) *MockOnboardingManager {
	mock := &MockOnboardingManager{ctrl: ctrl}
	mock.recorder = &MockOnboardingManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOnboardingManager) EXPECT() *MockOnboardingManagerMockRecorder {
	return m.recorder
}

// AcceptFirstAdmin mocks base method.
func (m *MockOnboardingManager) AcceptFirstAdmin(ctx context.Context, username, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptFirstAdmin", ctx, username, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptFirstAdmin indicates an expected call of AcceptFirstAdmin.
func (mr *MockOnboardingManagerMockRecorder) AcceptFirstAdmin(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptFirstAdmin", reflect.TypeOf((*MockOnboardingManager)(nil).AcceptFirstAdmin), ctx, username, password)
}

// AcceptInvite mocks base method.
func (m *MockOnboardingManager) AcceptInvite(ctx context.Context, token, username, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptInvite", ctx, token, username, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptInvite indicates an expected call of AcceptInvite.
func (mr *MockOnboardingManagerMockRecorder) AcceptInvite(ctx, token, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptInvite", reflect.TypeOf((*MockOnboardingManager)(nil).AcceptInvite), ctx, token, username, password)
}

// GenerateInvite mocks base method.
func (m *MockOnboardingManager) GenerateInvite(ctx context.Context, adminUserID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateInvite", ctx, adminUserID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateInvite indicates an expected call of GenerateInvite.
func (mr *MockOnboardingManagerMockRecorder) GenerateInvite(ctx, adminUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateInvite", reflect.TypeOf((*MockOnboardingManager)(nil).GenerateInvite), ctx, adminUserID)
}

// IsEmpty mocks base method.
func (m *MockOnboardingManager) IsEmpty(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmpty", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEmpty indicates an expected call of IsEmpty.
func (mr *MockOnboardingManagerMockRecorder) IsEmpty(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmpty", reflect.TypeOf((*MockOnboardingManager)(nil).IsEmpty), ctx)
}

// MockUserAdminManager is a mock of UserAdminManager interface.
type MockUserAdminManager struct {
	ctrl     *gomock.Controller
	recorder *MockUserAdminManagerMockRecorder
	isgomock struct{}
}

// MockUserAdminManagerMockRecorder is the mock recorder for MockUserAdminManager.
type MockUserAdminManagerMockRecorder struct {
	mock *MockUserAdminManager
}

// NewMockUserAdminManager creates a new mock instance.
func NewMockUserAdminManager(ctrl *gomock.Controller) *MockUserAdminManager {
	mock := &MockUserAdminManager{ctrl: ctrl}
	mock.recorder = &MockUserAdminManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAdminManager) EXPECT() *MockUserAdminManagerMockRecorder {
	return m.recorder
}

// ListUsers mocks base method.
func (m *MockUserAdminManager) ListUsers(ctx context.Context, adminUserID string) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, adminUserID)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserAdminManagerMockRecorder) ListUsers(ctx, adminUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserAdminManager)(nil).ListUsers), ctx, adminUserID)
}

// RevokeUser mocks base method.
func (m *MockUserAdminManager) RevokeUser(ctx context.Context, adminUserID, targetUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeUser", ctx, adminUserID, targetUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeUser indicates an expected call of RevokeUser.
func (mr *MockUserAdminManagerMockRecorder) RevokeUser(ctx, adminUserID, targetUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeUser", reflect.TypeOf((*MockUserAdminManager)(nil).RevokeUser), ctx, adminUserID, targetUserID)
}

// MockAPITokenManager is a mock of APITokenManager interface.
type MockAPITokenManager struct {
	ctrl     *gomock.Controller
	recorder *MockAPITokenManagerMockRecorder
	isgomock struct{}
}

// MockAPITokenManagerMockRecorder is the mock recorder for MockAPITokenManager.
type MockAPITokenManagerMockRecorder struct {
	mock *MockAPITokenManager
}

// NewMockAPITokenManager creates a new mock instance.
func NewMockAPITokenManager(ctrl *gomock.Controller) *MockAPITokenManager {
	mock := &MockAPITokenManager{ctrl: ctrl}
	mock.recorder = &MockAPITokenManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPITokenManager) EXPECT() *MockAPITokenManagerMockRecorder {
	return m.recorder
}

// CreateAPIToken mocks base method.
func (m *MockAPITokenManager) CreateAPIToken(ctx context.Context, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPIToken", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAPIToken indicates an expected call of CreateAPIToken.
func (mr *MockAPITokenManagerMockRecorder) CreateAPIToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPIToken", reflect.TypeOf((*MockAPITokenManager)(nil).CreateAPIToken), ctx, userID)
}

// ListAPITokens mocks base method.
func (m *MockAPITokenManager) ListAPITokens(ctx context.Context, adminUserID string) ([]*auth.APITokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAPITokens", ctx, adminUserID)
	ret0, _ := ret[0].([]*auth.APITokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAPITokens indicates an expected call of ListAPITokens.
func (mr *MockAPITokenManagerMockRecorder) ListAPITokens(ctx, adminUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAPITokens", reflect.TypeOf((*MockAPITokenManager)(nil).ListAPITokens), ctx, adminUserID)
}

// ResolveAPIToken mocks base method.
func (m *MockAPITokenManager) ResolveAPIToken(ctx context.Context, plainToken string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAPIToken", ctx, plainToken)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAPIToken indicates an expected call of ResolveAPIToken.
func (mr *MockAPITokenManagerMockRecorder) ResolveAPIToken(ctx, plainToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAPIToken", reflect.TypeOf((*MockAPITokenManager)(nil).ResolveAPIToken), ctx, plainToken)
}

// RevokeAPIToken mocks base method.
func (m *MockAPITokenManager) RevokeAPIToken(ctx context.Context, adminUserID, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAPIToken", ctx, adminUserID, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAPIToken indicates an expected call of RevokeAPIToken.
func (mr *MockAPITokenManagerMockRecorder) RevokeAPIToken(ctx, adminUserID, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAPIToken", reflect.TypeOf((*MockAPITokenManager)(nil).RevokeAPIToken), ctx, adminUserID, tokenID)
}

// MockAuthManager is a mock of AuthManager interface.
type MockAuthManager struct {
	ctrl     *gomock.Controller
	recorder *MockAuthManagerMockRecorder
	isgomock struct{}
}

// MockAuthManagerMockRecorder is the mock recorder for MockAuthManager.
type MockAuthManagerMockRecorder struct {
	mock *MockAuthManager
}

// NewMockAuthManager creates a new mock instance.
func NewMockAuthManager(ctrl *gomock.Controller) *MockAuthManager {
	mock := &MockAuthManager{ctrl: ctrl}
	mock.recorder = &MockAuthManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthManager) EXPECT() *MockAuthManagerMockRecorder {
	return m.recorder
}

// AcceptFirstAdmin mocks base method.
func (m *MockAuthManager) AcceptFirstAdmin(ctx context.Context, username, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptFirstAdmin", ctx, username, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptFirstAdmin indicates an expected call of AcceptFirstAdmin.
func (mr *MockAuthManagerMockRecorder) AcceptFirstAdmin(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptFirstAdmin", reflect.TypeOf((*MockAuthManager)(nil).AcceptFirstAdmin), ctx, username, password)
}

// AcceptInvite mocks base method.
func (m *MockAuthManager) AcceptInvite(ctx context.Context, token, username, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptInvite", ctx, token, username, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptInvite indicates an expected call of AcceptInvite.
func (mr *MockAuthManagerMockRecorder) AcceptInvite(ctx, token, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptInvite", reflect.TypeOf((*MockAuthManager)(nil).AcceptInvite), ctx, token, username, password)
}

// ChangePassword mocks base method.
func (m *MockAuthManager) ChangePassword(ctx context.Context, sessionID, oldPassword, newPassword, totpCode string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, sessionID, oldPassword, newPassword, totpCode)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockAuthManagerMockRecorder) ChangePassword(ctx, sessionID, oldPassword, newPassword, totpCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockAuthManager)(nil).ChangePassword), ctx, sessionID, oldPassword, newPassword, totpCode)
}

// CreateAPIToken mocks base method.
func (m *MockAuthManager) CreateAPIToken(ctx context.Context, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPIToken", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAPIToken indicates an expected call of CreateAPIToken.
func (mr *MockAuthManagerMockRecorder) CreateAPIToken(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPIToken", reflect.TypeOf((*MockAuthManager)(nil).CreateAPIToken), ctx, userID)
}

// GenerateInvite mocks base method.
func (m *MockAuthManager) GenerateInvite(ctx context.Context, adminUserID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateInvite", ctx, adminUserID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateInvite indicates an expected call of GenerateInvite.
func (mr *MockAuthManagerMockRecorder) GenerateInvite(ctx, adminUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateInvite", reflect.TypeOf((*MockAuthManager)(nil).GenerateInvite), ctx, adminUserID)
}

// GetSession mocks base method.
func (m *MockAuthManager) GetSession(ctx context.Context, sessionID string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, sessionID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockAuthManagerMockRecorder) GetSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockAuthManager)(nil).GetSession), ctx, sessionID)
}

// IsEmpty mocks base method.
func (m *MockAuthManager) IsEmpty(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmpty", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEmpty indicates an expected call of IsEmpty.
func (mr *MockAuthManagerMockRecorder) IsEmpty(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmpty", reflect.TypeOf((*MockAuthManager)(nil).IsEmpty), ctx)
}

// ListAPITokens mocks base method.
func (m *MockAuthManager) ListAPITokens(ctx context.Context, adminUserID string) ([]*auth.APITokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAPITokens", ctx, adminUserID)
	ret0, _ := ret[0].([]*auth.APITokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAPITokens indicates an expected call of ListAPITokens.
func (mr *MockAuthManagerMockRecorder) ListAPITokens(ctx, adminUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAPITokens", reflect.TypeOf((*MockAuthManager)(nil).ListAPITokens), ctx, adminUserID)
}

// ListUsers mocks base method.
func (m *MockAuthManager) ListUsers(ctx context.Context, adminUserID string) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, adminUserID)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockAuthManagerMockRecorder) ListUsers(ctx, adminUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockAuthManager)(nil).ListUsers), ctx, adminUserID)
}

// Login mocks base method.
func (m *MockAuthManager) Login(ctx context.Context, username, password, totpCode, userAgent, clientIP string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, username, password, totpCode, userAgent, clientIP)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthManagerMockRecorder) Login(ctx, username, password, totpCode, userAgent, clientIP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthManager)(nil).Login), ctx, username, password, totpCode, userAgent, clientIP)
}

// Logout mocks base method.
func (m *MockAuthManager) Logout(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthManagerMockRecorder) Logout(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthManager)(nil).Logout), ctx, sessionID)
}

// ResolveAPIToken mocks base method.
func (m *MockAuthManager) ResolveAPIToken(ctx context.Context, plainToken string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAPIToken", ctx, plainToken)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAPIToken indicates an expected call of ResolveAPIToken.
func (mr *MockAuthManagerMockRecorder) ResolveAPIToken(ctx, plainToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAPIToken", reflect.TypeOf((*MockAuthManager)(nil).ResolveAPIToken), ctx, plainToken)
}

// RevokeAPIToken mocks base method.
func (m *MockAuthManager) RevokeAPIToken(ctx context.Context, adminUserID, tokenID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAPIToken", ctx, adminUserID, tokenID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAPIToken indicates an expected call of RevokeAPIToken.
func (mr *MockAuthManagerMockRecorder) RevokeAPIToken(ctx, adminUserID, tokenID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAPIToken", reflect.TypeOf((*MockAuthManager)(nil).RevokeAPIToken), ctx, adminUserID, tokenID)
}

// RevokeUser mocks base method.
func (m *MockAuthManager) RevokeUser(ctx context.Context, adminUserID, targetUserID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeUser", ctx, adminUserID, targetUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeUser indicates an expected call of RevokeUser.
func (mr *MockAuthManagerMockRecorder) RevokeUser(ctx, adminUserID, targetUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeUser", reflect.TypeOf((*MockAuthManager)(nil).RevokeUser), ctx, adminUserID, targetUserID)
}

// MockRevealTokenStore is a mock of RevealTokenStore interface.
type MockRevealTokenStore struct {
	ctrl     *gomock.Controller
	recorder *MockRevealTokenStoreMockRecorder
	isgomock struct{}
}

// MockRevealTokenStoreMockRecorder is the mock recorder for MockRevealTokenStore.
type MockRevealTokenStoreMockRecorder struct {
	mock *MockRevealTokenStore
}

// NewMockRevealTokenStore creates a new mock instance.
func NewMockRevealTokenStore(ctrl *gomock.Controller) *MockRevealTokenStore {
	mock := &MockRevealTokenStore{ctrl: ctrl}
	mock.recorder = &MockRevealTokenStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRevealTokenStore) EXPECT() *MockRevealTokenStoreMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockRevealTokenStore) Consume(ctx context.Context, tok, noteID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, tok, noteID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockRevealTokenStoreMockRecorder) Consume(ctx, tok, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockRevealTokenStore)(nil).Consume), ctx, tok, noteID)
}

// Issue mocks base method.
func (m *MockRevealTokenStore) Issue(ctx context.Context, noteID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", ctx, noteID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MockRevealTokenStoreMockRecorder) Issue(ctx, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockRevealTokenStore)(nil).Issue), ctx, noteID)
}

// MockNoteManager is a mock of NoteManager interface.
type MockNoteManager struct {
	ctrl     *gomock.Controller
	recorder *MockNoteManagerMockRecorder
	isgomock struct{}
}

// MockNoteManagerMockRecorder is the mock recorder for MockNoteManager.
type MockNoteManagerMockRecorder struct {
	mock *MockNoteManager
}

// NewMockNoteManager creates a new mock instance.
func NewMockNoteManager(ctrl *gomock.Controller) *MockNoteManager {
	mock := &MockNoteManager{ctrl: ctrl}
	mock.recorder = &MockNoteManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteManager) EXPECT() *MockNoteManagerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNoteManager) Create(ctx context.Context, note *domain.Note) (*domain.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, note)
	ret0, _ := ret[0].(*domain.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNoteManagerMockRecorder) Create(ctx, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNoteManager)(nil).Create), ctx, note)
}

// Delete mocks base method.
func (m *MockNoteManager) Delete(ctx context.Context, id, editCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, editCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNoteManagerMockRecorder) Delete(ctx, id, editCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNoteManager)(nil).Delete), ctx, id, editCode)
}

// GetRendered mocks base method.
func (m *MockNoteManager) GetRendered(ctx context.Context, id string) (*domain.Note, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRendered", ctx, id)
	ret0, _ := ret[0].(*domain.Note)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRendered indicates an expected call of GetRendered.
func (mr *MockNoteManagerMockRecorder) GetRendered(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRendered", reflect.TypeOf((*MockNoteManager)(nil).GetRendered), ctx, id)
}

// GetRenderedPreloaded mocks base method.
func (m *MockNoteManager) GetRenderedPreloaded(ctx context.Context, id string, preloaded *domain.Note) (*domain.Note, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRenderedPreloaded", ctx, id, preloaded)
	ret0, _ := ret[0].(*domain.Note)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRenderedPreloaded indicates an expected call of GetRenderedPreloaded.
func (mr *MockNoteManagerMockRecorder) GetRenderedPreloaded(ctx, id, preloaded any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRenderedPreloaded", reflect.TypeOf((*MockNoteManager)(nil).GetRenderedPreloaded), ctx, id, preloaded)
}

// Peek mocks base method.
func (m *MockNoteManager) Peek(ctx context.Context, id string) (*domain.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Peek", ctx, id)
	ret0, _ := ret[0].(*domain.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Peek indicates an expected call of Peek.
func (mr *MockNoteManagerMockRecorder) Peek(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Peek", reflect.TypeOf((*MockNoteManager)(nil).Peek), ctx, id)
}

// Update mocks base method.
func (m *MockNoteManager) Update(ctx context.Context, id, editCode string, note *domain.Note) (*domain.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, editCode, note)
	ret0, _ := ret[0].(*domain.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNoteManagerMockRecorder) Update(ctx, id, editCode, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNoteManager)(nil).Update), ctx, id, editCode, note)
}

// View mocks base method.
func (m *MockNoteManager) View(ctx context.Context, id string) (*domain.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "View", ctx, id)
	ret0, _ := ret[0].(*domain.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// View indicates an expected call of View.
func (mr *MockNoteManagerMockRecorder) View(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "View", reflect.TypeOf((*MockNoteManager)(nil).View), ctx, id)
}

// ViewPreloaded mocks base method.
func (m *MockNoteManager) ViewPreloaded(ctx context.Context, id string, preloaded *domain.Note) (*domain.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewPreloaded", ctx, id, preloaded)
	ret0, _ := ret[0].(*domain.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewPreloaded indicates an expected call of ViewPreloaded.
func (mr *MockNoteManagerMockRecorder) ViewPreloaded(ctx, id, preloaded any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewPreloaded", reflect.TypeOf((*MockNoteManager)(nil).ViewPreloaded), ctx, id, preloaded)
}

// MockPinger is a mock of Pinger interface.
type MockPinger struct {
	ctrl     *gomock.Controller
	recorder *MockPingerMockRecorder
	isgomock struct{}
}

// MockPingerMockRecorder is the mock recorder for MockPinger.
type MockPingerMockRecorder struct {
	mock *MockPinger
}

// NewMockPinger creates a new mock instance.
func NewMockPinger(ctrl *gomock.Controller) *MockPinger {
	mock := &MockPinger{ctrl: ctrl}
	mock.recorder = &MockPingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPinger) EXPECT() *MockPingerMockRecorder {
	return m.recorder
}

// PingContext mocks base method.
func (m *MockPinger) PingContext(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingContext", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingContext indicates an expected call of PingContext.
func (mr *MockPingerMockRecorder) PingContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingContext", reflect.TypeOf((*MockPinger)(nil).PingContext), ctx)
}
