// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=handler_mocks_test.go -package=http_test
//

// Package http_test is a generated GoMock package.
package http_test

import (
	context "context"
	reflect "reflect"

	domain "github.com/partyzanex/padmark/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockNoteManager is a mock of NoteManager interface.
type MockNoteManager struct {
	ctrl     *gomock.Controller
	recorder *MockNoteManagerMockRecorder
	isgomock struct{}
}

// MockNoteManagerMockRecorder is the mock recorder for MockNoteManager.
type MockNoteManagerMockRecorder struct {
	mock *MockNoteManager
}

// NewMockNoteManager creates a new mock instance.
func NewMockNoteManager(ctrl *gomock.Controller) *MockNoteManager {
	mock := &MockNoteManager{ctrl: ctrl}
	mock.recorder = &MockNoteManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteManager) EXPECT() *MockNoteManagerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNoteManager) Create(ctx context.Context, note *domain.Note) (*domain.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, note)
	ret0, _ := ret[0].(*domain.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNoteManagerMockRecorder) Create(ctx, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNoteManager)(nil).Create), ctx, note)
}

// Delete mocks base method.
func (m *MockNoteManager) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNoteManagerMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNoteManager)(nil).Delete), ctx, id)
}

// GetRendered mocks base method.
func (m *MockNoteManager) GetRendered(ctx context.Context, id string) (*domain.Note, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRendered", ctx, id)
	ret0, _ := ret[0].(*domain.Note)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRendered indicates an expected call of GetRendered.
func (mr *MockNoteManagerMockRecorder) GetRendered(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRendered", reflect.TypeOf((*MockNoteManager)(nil).GetRendered), ctx, id)
}

// Update mocks base method.
func (m *MockNoteManager) Update(ctx context.Context, id string, note *domain.Note) (*domain.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, note)
	ret0, _ := ret[0].(*domain.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNoteManagerMockRecorder) Update(ctx, id, note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNoteManager)(nil).Update), ctx, id, note)
}

// View mocks base method.
func (m *MockNoteManager) View(ctx context.Context, id string) (*domain.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "View", ctx, id)
	ret0, _ := ret[0].(*domain.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// View indicates an expected call of View.
func (mr *MockNoteManagerMockRecorder) View(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "View", reflect.TypeOf((*MockNoteManager)(nil).View), ctx, id)
}

// MockPinger is a mock of Pinger interface.
type MockPinger struct {
	ctrl     *gomock.Controller
	recorder *MockPingerMockRecorder
	isgomock struct{}
}

// MockPingerMockRecorder is the mock recorder for MockPinger.
type MockPingerMockRecorder struct {
	mock *MockPinger
}

// NewMockPinger creates a new mock instance.
func NewMockPinger(ctrl *gomock.Controller) *MockPinger {
	mock := &MockPinger{ctrl: ctrl}
	mock.recorder = &MockPingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPinger) EXPECT() *MockPingerMockRecorder {
	return m.recorder
}

// PingContext mocks base method.
func (m *MockPinger) PingContext(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingContext", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingContext indicates an expected call of PingContext.
func (mr *MockPingerMockRecorder) PingContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingContext", reflect.TypeOf((*MockPinger)(nil).PingContext), ctx)
}
