// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source=manager.go -destination=manager_mocks_test.go -package=auth
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/partyzanex/padmark/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserStore is a mock of UserStore interface.
type MockUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserStoreMockRecorder
	isgomock struct{}
}

// MockUserStoreMockRecorder is the mock recorder for MockUserStore.
type MockUserStoreMockRecorder struct {
	mock *MockUserStore
}

// NewMockUserStore creates a new mock instance.
func NewMockUserStore(ctrl *gomock.Controller) *MockUserStore {
	mock := &MockUserStore{ctrl: ctrl}
	mock.recorder = &MockUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStore) EXPECT() *MockUserStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserStore) Create(ctx context.Context, u *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserStoreMockRecorder) Create(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserStore)(nil).Create), ctx, u)
}

// GetByID mocks base method.
func (m *MockUserStore) GetByID(ctx context.Context, id string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserStoreMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserStore)(nil).GetByID), ctx, id)
}

// GetByUsername mocks base method.
func (m *MockUserStore) GetByUsername(ctx context.Context, username string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockUserStoreMockRecorder) GetByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockUserStore)(nil).GetByUsername), ctx, username)
}

// List mocks base method.
func (m *MockUserStore) List(ctx context.Context) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserStoreMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserStore)(nil).List), ctx)
}

// Revoke mocks base method.
func (m *MockUserStore) Revoke(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockUserStoreMockRecorder) Revoke(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockUserStore)(nil).Revoke), ctx, id)
}

// UpdateLastLogin mocks base method.
func (m *MockUserStore) UpdateLastLogin(ctx context.Context, id string, t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", ctx, id, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockUserStoreMockRecorder) UpdateLastLogin(ctx, id, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockUserStore)(nil).UpdateLastLogin), ctx, id, t)
}

// UpdatePassword mocks base method.
func (m *MockUserStore) UpdatePassword(ctx context.Context, id, passwordHash string, kdfSalt []byte, totpSecret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, id, passwordHash, kdfSalt, totpSecret)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockUserStoreMockRecorder) UpdatePassword(ctx, id, passwordHash, kdfSalt, totpSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockUserStore)(nil).UpdatePassword), ctx, id, passwordHash, kdfSalt, totpSecret)
}

// UpdateTOTPCounter mocks base method.
func (m *MockUserStore) UpdateTOTPCounter(ctx context.Context, id string, counter int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTOTPCounter", ctx, id, counter)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTOTPCounter indicates an expected call of UpdateTOTPCounter.
func (mr *MockUserStoreMockRecorder) UpdateTOTPCounter(ctx, id, counter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTOTPCounter", reflect.TypeOf((*MockUserStore)(nil).UpdateTOTPCounter), ctx, id, counter)
}

// MockInviteStore is a mock of InviteStore interface.
type MockInviteStore struct {
	ctrl     *gomock.Controller
	recorder *MockInviteStoreMockRecorder
	isgomock struct{}
}

// MockInviteStoreMockRecorder is the mock recorder for MockInviteStore.
type MockInviteStoreMockRecorder struct {
	mock *MockInviteStore
}

// NewMockInviteStore creates a new mock instance.
func NewMockInviteStore(ctrl *gomock.Controller) *MockInviteStore {
	mock := &MockInviteStore{ctrl: ctrl}
	mock.recorder = &MockInviteStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInviteStore) EXPECT() *MockInviteStoreMockRecorder {
	return m.recorder
}

// Issue mocks base method.
func (m *MockInviteStore) Issue(ctx context.Context, createdByID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", ctx, createdByID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MockInviteStoreMockRecorder) Issue(ctx, createdByID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockInviteStore)(nil).Issue), ctx, createdByID)
}

// RedeemInvite mocks base method.
func (m *MockInviteStore) RedeemInvite(ctx context.Context, token, username string, usr *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedeemInvite", ctx, token, username, usr)
	ret0, _ := ret[0].(error)
	return ret0
}

// RedeemInvite indicates an expected call of RedeemInvite.
func (mr *MockInviteStoreMockRecorder) RedeemInvite(ctx, token, username, usr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedeemInvite", reflect.TypeOf((*MockInviteStore)(nil).RedeemInvite), ctx, token, username, usr)
}

// MockSessionStore is a mock of SessionStore interface.
type MockSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStoreMockRecorder
	isgomock struct{}
}

// MockSessionStoreMockRecorder is the mock recorder for MockSessionStore.
type MockSessionStoreMockRecorder struct {
	mock *MockSessionStore
}

// NewMockSessionStore creates a new mock instance.
func NewMockSessionStore(ctrl *gomock.Controller) *MockSessionStore {
	mock := &MockSessionStore{ctrl: ctrl}
	mock.recorder = &MockSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStore) EXPECT() *MockSessionStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionStore) Create(ctx context.Context, s *domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionStoreMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionStore)(nil).Create), ctx, s)
}

// Delete mocks base method.
func (m *MockSessionStore) Delete(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionStoreMockRecorder) Delete(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionStore)(nil).Delete), ctx, sessionID)
}

// DeleteByUserID mocks base method.
func (m *MockSessionStore) DeleteByUserID(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockSessionStoreMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockSessionStore)(nil).DeleteByUserID), ctx, userID)
}

// DeleteByUserIDExcept mocks base method.
func (m *MockSessionStore) DeleteByUserIDExcept(ctx context.Context, userID, exceptSessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserIDExcept", ctx, userID, exceptSessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserIDExcept indicates an expected call of DeleteByUserIDExcept.
func (mr *MockSessionStoreMockRecorder) DeleteByUserIDExcept(ctx, userID, exceptSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserIDExcept", reflect.TypeOf((*MockSessionStore)(nil).DeleteByUserIDExcept), ctx, userID, exceptSessionID)
}

// Get mocks base method.
func (m *MockSessionStore) Get(ctx context.Context, sessionID string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, sessionID)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionStoreMockRecorder) Get(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionStore)(nil).Get), ctx, sessionID)
}

// MockEncryptor is a mock of Encryptor interface.
type MockEncryptor struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptorMockRecorder
	isgomock struct{}
}

// MockEncryptorMockRecorder is the mock recorder for MockEncryptor.
type MockEncryptorMockRecorder struct {
	mock *MockEncryptor
}

// NewMockEncryptor creates a new mock instance.
func NewMockEncryptor(ctrl *gomock.Controller) *MockEncryptor {
	mock := &MockEncryptor{ctrl: ctrl}
	mock.recorder = &MockEncryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptor) EXPECT() *MockEncryptorMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockEncryptor) Decrypt(ciphertext, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ciphertext, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEncryptorMockRecorder) Decrypt(ciphertext, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockEncryptor)(nil).Decrypt), ciphertext, key)
}

// Encrypt mocks base method.
func (m *MockEncryptor) Encrypt(plaintext, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", plaintext, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncryptorMockRecorder) Encrypt(plaintext, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncryptor)(nil).Encrypt), plaintext, key)
}

// MockPasswordHasher is a mock of PasswordHasher interface.
type MockPasswordHasher struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordHasherMockRecorder
	isgomock struct{}
}

// MockPasswordHasherMockRecorder is the mock recorder for MockPasswordHasher.
type MockPasswordHasherMockRecorder struct {
	mock *MockPasswordHasher
}

// NewMockPasswordHasher creates a new mock instance.
func NewMockPasswordHasher(ctrl *gomock.Controller) *MockPasswordHasher {
	mock := &MockPasswordHasher{ctrl: ctrl}
	mock.recorder = &MockPasswordHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordHasher) EXPECT() *MockPasswordHasherMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockPasswordHasher) Hash(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockPasswordHasherMockRecorder) Hash(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockPasswordHasher)(nil).Hash), password)
}

// Verify mocks base method.
func (m *MockPasswordHasher) Verify(storedHash, password string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", storedHash, password)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockPasswordHasherMockRecorder) Verify(storedHash, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockPasswordHasher)(nil).Verify), storedHash, password)
}

// MockKeyDeriver is a mock of KeyDeriver interface.
type MockKeyDeriver struct {
	ctrl     *gomock.Controller
	recorder *MockKeyDeriverMockRecorder
	isgomock struct{}
}

// MockKeyDeriverMockRecorder is the mock recorder for MockKeyDeriver.
type MockKeyDeriverMockRecorder struct {
	mock *MockKeyDeriver
}

// NewMockKeyDeriver creates a new mock instance.
func NewMockKeyDeriver(ctrl *gomock.Controller) *MockKeyDeriver {
	mock := &MockKeyDeriver{ctrl: ctrl}
	mock.recorder = &MockKeyDeriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeyDeriver) EXPECT() *MockKeyDeriverMockRecorder {
	return m.recorder
}

// DeriveKey mocks base method.
func (m *MockKeyDeriver) DeriveKey(password, salt []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeriveKey", password, salt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeriveKey indicates an expected call of DeriveKey.
func (mr *MockKeyDeriverMockRecorder) DeriveKey(password, salt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeriveKey", reflect.TypeOf((*MockKeyDeriver)(nil).DeriveKey), password, salt)
}

// GenerateSalt mocks base method.
func (m *MockKeyDeriver) GenerateSalt() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSalt")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSalt indicates an expected call of GenerateSalt.
func (mr *MockKeyDeriverMockRecorder) GenerateSalt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSalt", reflect.TypeOf((*MockKeyDeriver)(nil).GenerateSalt))
}

// MockTOTPManager is a mock of TOTPManager interface.
type MockTOTPManager struct {
	ctrl     *gomock.Controller
	recorder *MockTOTPManagerMockRecorder
	isgomock struct{}
}

// MockTOTPManagerMockRecorder is the mock recorder for MockTOTPManager.
type MockTOTPManagerMockRecorder struct {
	mock *MockTOTPManager
}

// NewMockTOTPManager creates a new mock instance.
func NewMockTOTPManager(ctrl *gomock.Controller) *MockTOTPManager {
	mock := &MockTOTPManager{ctrl: ctrl}
	mock.recorder = &MockTOTPManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTOTPManager) EXPECT() *MockTOTPManagerMockRecorder {
	return m.recorder
}

// GenerateQRCode mocks base method.
func (m *MockTOTPManager) GenerateQRCode(issuer, account, secret string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateQRCode", issuer, account, secret)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateQRCode indicates an expected call of GenerateQRCode.
func (mr *MockTOTPManagerMockRecorder) GenerateQRCode(issuer, account, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateQRCode", reflect.TypeOf((*MockTOTPManager)(nil).GenerateQRCode), issuer, account, secret)
}

// GenerateSecret mocks base method.
func (m *MockTOTPManager) GenerateSecret() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSecret")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateSecret indicates an expected call of GenerateSecret.
func (mr *MockTOTPManagerMockRecorder) GenerateSecret() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSecret", reflect.TypeOf((*MockTOTPManager)(nil).GenerateSecret))
}

// ValidateWithCounter mocks base method.
func (m *MockTOTPManager) ValidateWithCounter(secret, code string) (bool, int64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateWithCounter", secret, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int64)
	return ret0, ret1
}

// ValidateWithCounter indicates an expected call of ValidateWithCounter.
func (mr *MockTOTPManagerMockRecorder) ValidateWithCounter(secret, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateWithCounter", reflect.TypeOf((*MockTOTPManager)(nil).ValidateWithCounter), secret, code)
}

// MockAPITokenStore is a mock of APITokenStore interface.
type MockAPITokenStore struct {
	ctrl     *gomock.Controller
	recorder *MockAPITokenStoreMockRecorder
	isgomock struct{}
}

// MockAPITokenStoreMockRecorder is the mock recorder for MockAPITokenStore.
type MockAPITokenStoreMockRecorder struct {
	mock *MockAPITokenStore
}

// NewMockAPITokenStore creates a new mock instance.
func NewMockAPITokenStore(ctrl *gomock.Controller) *MockAPITokenStore {
	mock := &MockAPITokenStore{ctrl: ctrl}
	mock.recorder = &MockAPITokenStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPITokenStore) EXPECT() *MockAPITokenStoreMockRecorder {
	return m.recorder
}

// CountByUser mocks base method.
func (m *MockAPITokenStore) CountByUser(ctx context.Context, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUser", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUser indicates an expected call of CountByUser.
func (mr *MockAPITokenStoreMockRecorder) CountByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUser", reflect.TypeOf((*MockAPITokenStore)(nil).CountByUser), ctx, userID)
}

// Create mocks base method.
func (m *MockAPITokenStore) Create(ctx context.Context, t *domain.APIToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAPITokenStoreMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAPITokenStore)(nil).Create), ctx, t)
}

// GetByHash mocks base method.
func (m *MockAPITokenStore) GetByHash(ctx context.Context, tokenHash string) (*domain.APIToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", ctx, tokenHash)
	ret0, _ := ret[0].(*domain.APIToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockAPITokenStoreMockRecorder) GetByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockAPITokenStore)(nil).GetByHash), ctx, tokenHash)
}

// List mocks base method.
func (m *MockAPITokenStore) List(ctx context.Context) ([]*domain.APIToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.APIToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAPITokenStoreMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAPITokenStore)(nil).List), ctx)
}

// RevokeByHash mocks base method.
func (m *MockAPITokenStore) RevokeByHash(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeByHash", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeByHash indicates an expected call of RevokeByHash.
func (mr *MockAPITokenStoreMockRecorder) RevokeByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeByHash", reflect.TypeOf((*MockAPITokenStore)(nil).RevokeByHash), ctx, tokenHash)
}

// UpdateLastUsed mocks base method.
func (m *MockAPITokenStore) UpdateLastUsed(ctx context.Context, tokenHash string, t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastUsed", ctx, tokenHash, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastUsed indicates an expected call of UpdateLastUsed.
func (mr *MockAPITokenStoreMockRecorder) UpdateLastUsed(ctx, tokenHash, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUsed", reflect.TypeOf((*MockAPITokenStore)(nil).UpdateLastUsed), ctx, tokenHash, t)
}
