// Code generated by ogen, DO NOT EDIT.

package ogenapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateNoteOperation OperationName = "CreateNote"
	DeleteNoteOperation OperationName = "DeleteNote"
	GetNoteOperation    OperationName = "GetNote"
	HealthzOperation    OperationName = "Healthz"
	ReadyzOperation     OperationName = "Readyz"
	UpdateNoteOperation OperationName = "UpdateNote"
)
