// Code generated by ogen, DO NOT EDIT.

package ogenapi

import (
	"time"

	"github.com/go-faster/errors"
)

type CreateNoteBadRequest ErrorResponse

func (*CreateNoteBadRequest) createNoteRes() {}

type CreateNoteConflict ErrorResponse

func (*CreateNoteConflict) createNoteRes() {}

type CreateNoteInternalServerError ErrorResponse

func (*CreateNoteInternalServerError) createNoteRes() {}

// Ref: #/components/schemas/CreateNoteRequest
type CreateNoteRequest struct {
	// Human-readable title shown in the note header.
	Title OptString `json:"title"`
	// Note body. Interpreted as Markdown unless `content_type` is `text/plain`.
	Content string `json:"content"`
	// MIME type of `content`; controls rendering on the view page.
	ContentType OptCreateNoteRequestContentType `json:"content_type"`
	// Custom URL-friendly identifier. Must match `[a-zA-Z0-9_-]+`.
	// If omitted a 10-character random slug is generated.
	// Returns `409` if the slug is already taken.
	Slug OptString `json:"slug"`
	// When `true` the note self-destructs after the first read.
	// If `ttl` is also provided the note is not deleted immediately but expires `ttl`
	// seconds after the first read.
	BurnAfterReading OptBool `json:"burn_after_reading"`
	// Grace period in seconds after the first read before the note expires.
	// Only meaningful when `burn_after_reading` is `true`.
	// `0` means the note is deleted immediately when it is first revealed.
	// Omitted means the same as `0` (immediate burn after reading).
	TTL OptInt64 `json:"ttl"`
	// Optional custom edit code. If omitted a random 12-character code is generated.
	// Intended for CLI and automation use; the web UI does not expose this field.
	EditCode OptString `json:"edit_code"`
	// Who may read the note: `public` (anyone), `authenticated` (any valid bearer token or
	// session, not just the creator), or `owner` (only the exact credential that created
	// it — see "Edit codes and ownership" above). Meaningful when the server is started
	// with `--auth-tokens` and/or `--enable-accounts`; `owner` additionally requires the
	// note to actually have an owner, i.e. `--enable-accounts` and an authenticated caller
	// — otherwise the request is rejected with `422`.
	Privacy OptCreateNoteRequestPrivacy `json:"privacy"`
}

// GetTitle returns the value of Title.
func (s *CreateNoteRequest) GetTitle() OptString {
	return s.Title
}

// GetContent returns the value of Content.
func (s *CreateNoteRequest) GetContent() string {
	return s.Content
}

// GetContentType returns the value of ContentType.
func (s *CreateNoteRequest) GetContentType() OptCreateNoteRequestContentType {
	return s.ContentType
}

// GetSlug returns the value of Slug.
func (s *CreateNoteRequest) GetSlug() OptString {
	return s.Slug
}

// GetBurnAfterReading returns the value of BurnAfterReading.
func (s *CreateNoteRequest) GetBurnAfterReading() OptBool {
	return s.BurnAfterReading
}

// GetTTL returns the value of TTL.
func (s *CreateNoteRequest) GetTTL() OptInt64 {
	return s.TTL
}

// GetEditCode returns the value of EditCode.
func (s *CreateNoteRequest) GetEditCode() OptString {
	return s.EditCode
}

// GetPrivacy returns the value of Privacy.
func (s *CreateNoteRequest) GetPrivacy() OptCreateNoteRequestPrivacy {
	return s.Privacy
}

// SetTitle sets the value of Title.
func (s *CreateNoteRequest) SetTitle(val OptString) {
	s.Title = val
}

// SetContent sets the value of Content.
func (s *CreateNoteRequest) SetContent(val string) {
	s.Content = val
}

// SetContentType sets the value of ContentType.
func (s *CreateNoteRequest) SetContentType(val OptCreateNoteRequestContentType) {
	s.ContentType = val
}

// SetSlug sets the value of Slug.
func (s *CreateNoteRequest) SetSlug(val OptString) {
	s.Slug = val
}

// SetBurnAfterReading sets the value of BurnAfterReading.
func (s *CreateNoteRequest) SetBurnAfterReading(val OptBool) {
	s.BurnAfterReading = val
}

// SetTTL sets the value of TTL.
func (s *CreateNoteRequest) SetTTL(val OptInt64) {
	s.TTL = val
}

// SetEditCode sets the value of EditCode.
func (s *CreateNoteRequest) SetEditCode(val OptString) {
	s.EditCode = val
}

// SetPrivacy sets the value of Privacy.
func (s *CreateNoteRequest) SetPrivacy(val OptCreateNoteRequestPrivacy) {
	s.Privacy = val
}

// MIME type of `content`; controls rendering on the view page.
type CreateNoteRequestContentType string

const (
	CreateNoteRequestContentTypeTextMarkdown CreateNoteRequestContentType = "text/markdown"
	CreateNoteRequestContentTypeTextPlain    CreateNoteRequestContentType = "text/plain"
)

// AllValues returns all CreateNoteRequestContentType values.
func (CreateNoteRequestContentType) AllValues() []CreateNoteRequestContentType {
	return []CreateNoteRequestContentType{
		CreateNoteRequestContentTypeTextMarkdown,
		CreateNoteRequestContentTypeTextPlain,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateNoteRequestContentType) MarshalText() ([]byte, error) {
	switch s {
	case CreateNoteRequestContentTypeTextMarkdown:
		return []byte(s), nil
	case CreateNoteRequestContentTypeTextPlain:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateNoteRequestContentType) UnmarshalText(data []byte) error {
	switch CreateNoteRequestContentType(data) {
	case CreateNoteRequestContentTypeTextMarkdown:
		*s = CreateNoteRequestContentTypeTextMarkdown
		return nil
	case CreateNoteRequestContentTypeTextPlain:
		*s = CreateNoteRequestContentTypeTextPlain
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateNoteRequestEntityTooLarge ErrorResponse

func (*CreateNoteRequestEntityTooLarge) createNoteRes() {}

// Who may read the note: `public` (anyone), `authenticated` (any valid bearer token or
// session, not just the creator), or `owner` (only the exact credential that created
// it — see "Edit codes and ownership" above). Meaningful when the server is started
// with `--auth-tokens` and/or `--enable-accounts`; `owner` additionally requires the
// note to actually have an owner, i.e. `--enable-accounts` and an authenticated caller
// — otherwise the request is rejected with `422`.
type CreateNoteRequestPrivacy string

const (
	CreateNoteRequestPrivacyPublic        CreateNoteRequestPrivacy = "public"
	CreateNoteRequestPrivacyAuthenticated CreateNoteRequestPrivacy = "authenticated"
	CreateNoteRequestPrivacyOwner         CreateNoteRequestPrivacy = "owner"
)

// AllValues returns all CreateNoteRequestPrivacy values.
func (CreateNoteRequestPrivacy) AllValues() []CreateNoteRequestPrivacy {
	return []CreateNoteRequestPrivacy{
		CreateNoteRequestPrivacyPublic,
		CreateNoteRequestPrivacyAuthenticated,
		CreateNoteRequestPrivacyOwner,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateNoteRequestPrivacy) MarshalText() ([]byte, error) {
	switch s {
	case CreateNoteRequestPrivacyPublic:
		return []byte(s), nil
	case CreateNoteRequestPrivacyAuthenticated:
		return []byte(s), nil
	case CreateNoteRequestPrivacyOwner:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateNoteRequestPrivacy) UnmarshalText(data []byte) error {
	switch CreateNoteRequestPrivacy(data) {
	case CreateNoteRequestPrivacyPublic:
		*s = CreateNoteRequestPrivacyPublic
		return nil
	case CreateNoteRequestPrivacyAuthenticated:
		*s = CreateNoteRequestPrivacyAuthenticated
		return nil
	case CreateNoteRequestPrivacyOwner:
		*s = CreateNoteRequestPrivacyOwner
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Merged schema.
// Ref: #/components/schemas/CreateNoteResponse
type CreateNoteResponse struct {
	// Unique slug identifying the note.
	ID string `json:"id"`
	// Note title.
	Title string `json:"title"`
	// Note body (Markdown or plain text depending on `content_type`).
	Content string `json:"content"`
	// MIME type of `content`.
	ContentType CreateNoteResponseContentType `json:"content_type"`
	// Number of times the note has been fetched via GET.
	Views int `json:"views"`
	// `true` until the first read (or permanently `false` for non-burn notes).
	// After the first read of a note with a TTL this becomes `false` and `expires_at`
	// is set.
	BurnAfterReading bool `json:"burn_after_reading"`
	// Who may read the note. See `CreateNoteRequest.privacy` for the exact semantics of
	// each value.
	Privacy OptCreateNoteResponsePrivacy `json:"privacy"`
	// ISO 8601 timestamp after which the note is inaccessible.
	// Set on the first read for burn-after-reading notes that have a TTL.
	// `null` for notes that are not expiring.
	ExpiresAt OptNilDateTime `json:"expires_at"`
	// Creation timestamp (UTC).
	CreatedAt time.Time `json:"created_at"`
	// Last-update timestamp (UTC).
	UpdatedAt time.Time `json:"updated_at"`
	// One-time secret required for future `PUT` and `DELETE` requests.
	// This is the only time `edit_code` is returned — store it securely.
	EditCode string `json:"edit_code"`
}

// GetID returns the value of ID.
func (s *CreateNoteResponse) GetID() string {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *CreateNoteResponse) GetTitle() string {
	return s.Title
}

// GetContent returns the value of Content.
func (s *CreateNoteResponse) GetContent() string {
	return s.Content
}

// GetContentType returns the value of ContentType.
func (s *CreateNoteResponse) GetContentType() CreateNoteResponseContentType {
	return s.ContentType
}

// GetViews returns the value of Views.
func (s *CreateNoteResponse) GetViews() int {
	return s.Views
}

// GetBurnAfterReading returns the value of BurnAfterReading.
func (s *CreateNoteResponse) GetBurnAfterReading() bool {
	return s.BurnAfterReading
}

// GetPrivacy returns the value of Privacy.
func (s *CreateNoteResponse) GetPrivacy() OptCreateNoteResponsePrivacy {
	return s.Privacy
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *CreateNoteResponse) GetExpiresAt() OptNilDateTime {
	return s.ExpiresAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CreateNoteResponse) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *CreateNoteResponse) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetEditCode returns the value of EditCode.
func (s *CreateNoteResponse) GetEditCode() string {
	return s.EditCode
}

// SetID sets the value of ID.
func (s *CreateNoteResponse) SetID(val string) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *CreateNoteResponse) SetTitle(val string) {
	s.Title = val
}

// SetContent sets the value of Content.
func (s *CreateNoteResponse) SetContent(val string) {
	s.Content = val
}

// SetContentType sets the value of ContentType.
func (s *CreateNoteResponse) SetContentType(val CreateNoteResponseContentType) {
	s.ContentType = val
}

// SetViews sets the value of Views.
func (s *CreateNoteResponse) SetViews(val int) {
	s.Views = val
}

// SetBurnAfterReading sets the value of BurnAfterReading.
func (s *CreateNoteResponse) SetBurnAfterReading(val bool) {
	s.BurnAfterReading = val
}

// SetPrivacy sets the value of Privacy.
func (s *CreateNoteResponse) SetPrivacy(val OptCreateNoteResponsePrivacy) {
	s.Privacy = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *CreateNoteResponse) SetExpiresAt(val OptNilDateTime) {
	s.ExpiresAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CreateNoteResponse) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *CreateNoteResponse) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetEditCode sets the value of EditCode.
func (s *CreateNoteResponse) SetEditCode(val string) {
	s.EditCode = val
}

// MIME type of `content`.
type CreateNoteResponseContentType string

const (
	CreateNoteResponseContentTypeTextMarkdown CreateNoteResponseContentType = "text/markdown"
	CreateNoteResponseContentTypeTextPlain    CreateNoteResponseContentType = "text/plain"
)

// AllValues returns all CreateNoteResponseContentType values.
func (CreateNoteResponseContentType) AllValues() []CreateNoteResponseContentType {
	return []CreateNoteResponseContentType{
		CreateNoteResponseContentTypeTextMarkdown,
		CreateNoteResponseContentTypeTextPlain,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateNoteResponseContentType) MarshalText() ([]byte, error) {
	switch s {
	case CreateNoteResponseContentTypeTextMarkdown:
		return []byte(s), nil
	case CreateNoteResponseContentTypeTextPlain:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateNoteResponseContentType) UnmarshalText(data []byte) error {
	switch CreateNoteResponseContentType(data) {
	case CreateNoteResponseContentTypeTextMarkdown:
		*s = CreateNoteResponseContentTypeTextMarkdown
		return nil
	case CreateNoteResponseContentTypeTextPlain:
		*s = CreateNoteResponseContentTypeTextPlain
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// CreateNoteResponseHeaders wraps CreateNoteResponse with response headers.
type CreateNoteResponseHeaders struct {
	Location OptString
	Response CreateNoteResponse
}

// GetLocation returns the value of Location.
func (s *CreateNoteResponseHeaders) GetLocation() OptString {
	return s.Location
}

// GetResponse returns the value of Response.
func (s *CreateNoteResponseHeaders) GetResponse() CreateNoteResponse {
	return s.Response
}

// SetLocation sets the value of Location.
func (s *CreateNoteResponseHeaders) SetLocation(val OptString) {
	s.Location = val
}

// SetResponse sets the value of Response.
func (s *CreateNoteResponseHeaders) SetResponse(val CreateNoteResponse) {
	s.Response = val
}

func (*CreateNoteResponseHeaders) createNoteRes() {}

// Who may read the note. See `CreateNoteRequest.privacy` for the exact semantics of
// each value.
type CreateNoteResponsePrivacy string

const (
	CreateNoteResponsePrivacyPublic        CreateNoteResponsePrivacy = "public"
	CreateNoteResponsePrivacyAuthenticated CreateNoteResponsePrivacy = "authenticated"
	CreateNoteResponsePrivacyOwner         CreateNoteResponsePrivacy = "owner"
)

// AllValues returns all CreateNoteResponsePrivacy values.
func (CreateNoteResponsePrivacy) AllValues() []CreateNoteResponsePrivacy {
	return []CreateNoteResponsePrivacy{
		CreateNoteResponsePrivacyPublic,
		CreateNoteResponsePrivacyAuthenticated,
		CreateNoteResponsePrivacyOwner,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateNoteResponsePrivacy) MarshalText() ([]byte, error) {
	switch s {
	case CreateNoteResponsePrivacyPublic:
		return []byte(s), nil
	case CreateNoteResponsePrivacyAuthenticated:
		return []byte(s), nil
	case CreateNoteResponsePrivacyOwner:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateNoteResponsePrivacy) UnmarshalText(data []byte) error {
	switch CreateNoteResponsePrivacy(data) {
	case CreateNoteResponsePrivacyPublic:
		*s = CreateNoteResponsePrivacyPublic
		return nil
	case CreateNoteResponsePrivacyAuthenticated:
		*s = CreateNoteResponsePrivacyAuthenticated
		return nil
	case CreateNoteResponsePrivacyOwner:
		*s = CreateNoteResponsePrivacyOwner
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateNoteUnauthorized ErrorResponse

func (*CreateNoteUnauthorized) createNoteRes() {}

type CreateNoteUnprocessableEntity ErrorResponse

func (*CreateNoteUnprocessableEntity) createNoteRes() {}

type DeleteNoteForbidden ErrorResponse

func (*DeleteNoteForbidden) deleteNoteRes() {}

type DeleteNoteInternalServerError ErrorResponse

func (*DeleteNoteInternalServerError) deleteNoteRes() {}

// DeleteNoteNoContent is response for DeleteNote operation.
type DeleteNoteNoContent struct{}

func (*DeleteNoteNoContent) deleteNoteRes() {}

type DeleteNoteNotFound ErrorResponse

func (*DeleteNoteNotFound) deleteNoteRes() {}

type DeleteNoteUnauthorized ErrorResponse

func (*DeleteNoteUnauthorized) deleteNoteRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// Human-readable error description.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

func (*ErrorResponse) readyzRes() {}

type GetNoteGone ErrorResponse

func (*GetNoteGone) getNoteRes() {}

type GetNoteInternalServerError ErrorResponse

func (*GetNoteInternalServerError) getNoteRes() {}

type GetNoteNotFound ErrorResponse

func (*GetNoteNotFound) getNoteRes() {}

// HealthzOK is response for Healthz operation.
type HealthzOK struct{}

// Ref: #/components/schemas/NoteResponse
type NoteResponse struct {
	// Unique slug identifying the note.
	ID string `json:"id"`
	// Note title.
	Title string `json:"title"`
	// Note body (Markdown or plain text depending on `content_type`).
	Content string `json:"content"`
	// MIME type of `content`.
	ContentType NoteResponseContentType `json:"content_type"`
	// Number of times the note has been fetched via GET.
	Views int `json:"views"`
	// `true` until the first read (or permanently `false` for non-burn notes).
	// After the first read of a note with a TTL this becomes `false` and `expires_at`
	// is set.
	BurnAfterReading bool `json:"burn_after_reading"`
	// Who may read the note. See `CreateNoteRequest.privacy` for the exact semantics of
	// each value.
	Privacy OptNoteResponsePrivacy `json:"privacy"`
	// ISO 8601 timestamp after which the note is inaccessible.
	// Set on the first read for burn-after-reading notes that have a TTL.
	// `null` for notes that are not expiring.
	ExpiresAt OptNilDateTime `json:"expires_at"`
	// Creation timestamp (UTC).
	CreatedAt time.Time `json:"created_at"`
	// Last-update timestamp (UTC).
	UpdatedAt time.Time `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *NoteResponse) GetID() string {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *NoteResponse) GetTitle() string {
	return s.Title
}

// GetContent returns the value of Content.
func (s *NoteResponse) GetContent() string {
	return s.Content
}

// GetContentType returns the value of ContentType.
func (s *NoteResponse) GetContentType() NoteResponseContentType {
	return s.ContentType
}

// GetViews returns the value of Views.
func (s *NoteResponse) GetViews() int {
	return s.Views
}

// GetBurnAfterReading returns the value of BurnAfterReading.
func (s *NoteResponse) GetBurnAfterReading() bool {
	return s.BurnAfterReading
}

// GetPrivacy returns the value of Privacy.
func (s *NoteResponse) GetPrivacy() OptNoteResponsePrivacy {
	return s.Privacy
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *NoteResponse) GetExpiresAt() OptNilDateTime {
	return s.ExpiresAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *NoteResponse) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *NoteResponse) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *NoteResponse) SetID(val string) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *NoteResponse) SetTitle(val string) {
	s.Title = val
}

// SetContent sets the value of Content.
func (s *NoteResponse) SetContent(val string) {
	s.Content = val
}

// SetContentType sets the value of ContentType.
func (s *NoteResponse) SetContentType(val NoteResponseContentType) {
	s.ContentType = val
}

// SetViews sets the value of Views.
func (s *NoteResponse) SetViews(val int) {
	s.Views = val
}

// SetBurnAfterReading sets the value of BurnAfterReading.
func (s *NoteResponse) SetBurnAfterReading(val bool) {
	s.BurnAfterReading = val
}

// SetPrivacy sets the value of Privacy.
func (s *NoteResponse) SetPrivacy(val OptNoteResponsePrivacy) {
	s.Privacy = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *NoteResponse) SetExpiresAt(val OptNilDateTime) {
	s.ExpiresAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *NoteResponse) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *NoteResponse) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*NoteResponse) getNoteRes()    {}
func (*NoteResponse) updateNoteRes() {}

// MIME type of `content`.
type NoteResponseContentType string

const (
	NoteResponseContentTypeTextMarkdown NoteResponseContentType = "text/markdown"
	NoteResponseContentTypeTextPlain    NoteResponseContentType = "text/plain"
)

// AllValues returns all NoteResponseContentType values.
func (NoteResponseContentType) AllValues() []NoteResponseContentType {
	return []NoteResponseContentType{
		NoteResponseContentTypeTextMarkdown,
		NoteResponseContentTypeTextPlain,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s NoteResponseContentType) MarshalText() ([]byte, error) {
	switch s {
	case NoteResponseContentTypeTextMarkdown:
		return []byte(s), nil
	case NoteResponseContentTypeTextPlain:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *NoteResponseContentType) UnmarshalText(data []byte) error {
	switch NoteResponseContentType(data) {
	case NoteResponseContentTypeTextMarkdown:
		*s = NoteResponseContentTypeTextMarkdown
		return nil
	case NoteResponseContentTypeTextPlain:
		*s = NoteResponseContentTypeTextPlain
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Who may read the note. See `CreateNoteRequest.privacy` for the exact semantics of
// each value.
type NoteResponsePrivacy string

const (
	NoteResponsePrivacyPublic        NoteResponsePrivacy = "public"
	NoteResponsePrivacyAuthenticated NoteResponsePrivacy = "authenticated"
	NoteResponsePrivacyOwner         NoteResponsePrivacy = "owner"
)

// AllValues returns all NoteResponsePrivacy values.
func (NoteResponsePrivacy) AllValues() []NoteResponsePrivacy {
	return []NoteResponsePrivacy{
		NoteResponsePrivacyPublic,
		NoteResponsePrivacyAuthenticated,
		NoteResponsePrivacyOwner,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s NoteResponsePrivacy) MarshalText() ([]byte, error) {
	switch s {
	case NoteResponsePrivacyPublic:
		return []byte(s), nil
	case NoteResponsePrivacyAuthenticated:
		return []byte(s), nil
	case NoteResponsePrivacyOwner:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *NoteResponsePrivacy) UnmarshalText(data []byte) error {
	switch NoteResponsePrivacy(data) {
	case NoteResponsePrivacyPublic:
		*s = NoteResponsePrivacyPublic
		return nil
	case NoteResponsePrivacyAuthenticated:
		*s = NoteResponsePrivacyAuthenticated
		return nil
	case NoteResponsePrivacyOwner:
		*s = NoteResponsePrivacyOwner
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateNoteRequestContentType returns new OptCreateNoteRequestContentType with value set to v.
func NewOptCreateNoteRequestContentType(v CreateNoteRequestContentType) OptCreateNoteRequestContentType {
	return OptCreateNoteRequestContentType{
		Value: v,
		Set:   true,
	}
}

// OptCreateNoteRequestContentType is optional CreateNoteRequestContentType.
type OptCreateNoteRequestContentType struct {
	Value CreateNoteRequestContentType
	Set   bool
}

// IsSet returns true if OptCreateNoteRequestContentType was set.
func (o OptCreateNoteRequestContentType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateNoteRequestContentType) Reset() {
	var v CreateNoteRequestContentType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateNoteRequestContentType) SetTo(v CreateNoteRequestContentType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateNoteRequestContentType) Get() (v CreateNoteRequestContentType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateNoteRequestContentType) Or(d CreateNoteRequestContentType) CreateNoteRequestContentType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateNoteRequestPrivacy returns new OptCreateNoteRequestPrivacy with value set to v.
func NewOptCreateNoteRequestPrivacy(v CreateNoteRequestPrivacy) OptCreateNoteRequestPrivacy {
	return OptCreateNoteRequestPrivacy{
		Value: v,
		Set:   true,
	}
}

// OptCreateNoteRequestPrivacy is optional CreateNoteRequestPrivacy.
type OptCreateNoteRequestPrivacy struct {
	Value CreateNoteRequestPrivacy
	Set   bool
}

// IsSet returns true if OptCreateNoteRequestPrivacy was set.
func (o OptCreateNoteRequestPrivacy) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateNoteRequestPrivacy) Reset() {
	var v CreateNoteRequestPrivacy
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateNoteRequestPrivacy) SetTo(v CreateNoteRequestPrivacy) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateNoteRequestPrivacy) Get() (v CreateNoteRequestPrivacy, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateNoteRequestPrivacy) Or(d CreateNoteRequestPrivacy) CreateNoteRequestPrivacy {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateNoteResponsePrivacy returns new OptCreateNoteResponsePrivacy with value set to v.
func NewOptCreateNoteResponsePrivacy(v CreateNoteResponsePrivacy) OptCreateNoteResponsePrivacy {
	return OptCreateNoteResponsePrivacy{
		Value: v,
		Set:   true,
	}
}

// OptCreateNoteResponsePrivacy is optional CreateNoteResponsePrivacy.
type OptCreateNoteResponsePrivacy struct {
	Value CreateNoteResponsePrivacy
	Set   bool
}

// IsSet returns true if OptCreateNoteResponsePrivacy was set.
func (o OptCreateNoteResponsePrivacy) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateNoteResponsePrivacy) Reset() {
	var v CreateNoteResponsePrivacy
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateNoteResponsePrivacy) SetTo(v CreateNoteResponsePrivacy) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateNoteResponsePrivacy) Get() (v CreateNoteResponsePrivacy, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateNoteResponsePrivacy) Or(d CreateNoteResponsePrivacy) CreateNoteResponsePrivacy {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNoteResponsePrivacy returns new OptNoteResponsePrivacy with value set to v.
func NewOptNoteResponsePrivacy(v NoteResponsePrivacy) OptNoteResponsePrivacy {
	return OptNoteResponsePrivacy{
		Value: v,
		Set:   true,
	}
}

// OptNoteResponsePrivacy is optional NoteResponsePrivacy.
type OptNoteResponsePrivacy struct {
	Value NoteResponsePrivacy
	Set   bool
}

// IsSet returns true if OptNoteResponsePrivacy was set.
func (o OptNoteResponsePrivacy) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNoteResponsePrivacy) Reset() {
	var v NoteResponsePrivacy
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptNoteResponsePrivacy) SetTo(v NoteResponsePrivacy) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNoteResponsePrivacy) Get() (v NoteResponsePrivacy, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNoteResponsePrivacy) Or(d NoteResponsePrivacy) NoteResponsePrivacy {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateNoteRequestContentType returns new OptUpdateNoteRequestContentType with value set to v.
func NewOptUpdateNoteRequestContentType(v UpdateNoteRequestContentType) OptUpdateNoteRequestContentType {
	return OptUpdateNoteRequestContentType{
		Value: v,
		Set:   true,
	}
}

// OptUpdateNoteRequestContentType is optional UpdateNoteRequestContentType.
type OptUpdateNoteRequestContentType struct {
	Value UpdateNoteRequestContentType
	Set   bool
}

// IsSet returns true if OptUpdateNoteRequestContentType was set.
func (o OptUpdateNoteRequestContentType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateNoteRequestContentType) Reset() {
	var v UpdateNoteRequestContentType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateNoteRequestContentType) SetTo(v UpdateNoteRequestContentType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateNoteRequestContentType) Get() (v UpdateNoteRequestContentType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateNoteRequestContentType) Or(d UpdateNoteRequestContentType) UpdateNoteRequestContentType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateNoteRequestPrivacy returns new OptUpdateNoteRequestPrivacy with value set to v.
func NewOptUpdateNoteRequestPrivacy(v UpdateNoteRequestPrivacy) OptUpdateNoteRequestPrivacy {
	return OptUpdateNoteRequestPrivacy{
		Value: v,
		Set:   true,
	}
}

// OptUpdateNoteRequestPrivacy is optional UpdateNoteRequestPrivacy.
type OptUpdateNoteRequestPrivacy struct {
	Value UpdateNoteRequestPrivacy
	Set   bool
}

// IsSet returns true if OptUpdateNoteRequestPrivacy was set.
func (o OptUpdateNoteRequestPrivacy) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateNoteRequestPrivacy) Reset() {
	var v UpdateNoteRequestPrivacy
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateNoteRequestPrivacy) SetTo(v UpdateNoteRequestPrivacy) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateNoteRequestPrivacy) Get() (v UpdateNoteRequestPrivacy, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateNoteRequestPrivacy) Or(d UpdateNoteRequestPrivacy) UpdateNoteRequestPrivacy {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// ReadyzOK is response for Readyz operation.
type ReadyzOK struct{}

func (*ReadyzOK) readyzRes() {}

type UpdateNoteBadRequest ErrorResponse

func (*UpdateNoteBadRequest) updateNoteRes() {}

type UpdateNoteForbidden ErrorResponse

func (*UpdateNoteForbidden) updateNoteRes() {}

type UpdateNoteInternalServerError ErrorResponse

func (*UpdateNoteInternalServerError) updateNoteRes() {}

type UpdateNoteNotFound ErrorResponse

func (*UpdateNoteNotFound) updateNoteRes() {}

// Ref: #/components/schemas/UpdateNoteRequest
type UpdateNoteRequest struct {
	// New title.
	Title OptString `json:"title"`
	// New body.
	Content string `json:"content"`
	// New content type; defaults to the note's current type when omitted.
	ContentType OptUpdateNoteRequestContentType `json:"content_type"`
	// The edit code returned when the note was created. May be omitted when the request is
	// authenticated (bearer token or session) as the note's owner — see
	// "Edit codes and ownership" above.
	EditCode OptString `json:"edit_code"`
	// Update the burn-after-reading flag.
	BurnAfterReading OptBool `json:"burn_after_reading"`
	// New TTL in seconds (grace period after first read).
	// Only meaningful when `burn_after_reading` is `true`.
	// `0` means the note is deleted immediately when it is first revealed.
	TTL OptInt64 `json:"ttl"`
	// Update the privacy level. See `CreateNoteRequest.privacy` for the exact semantics of
	// each value. Omitted keeps the note's current privacy level.
	Privacy OptUpdateNoteRequestPrivacy `json:"privacy"`
}

// GetTitle returns the value of Title.
func (s *UpdateNoteRequest) GetTitle() OptString {
	return s.Title
}

// GetContent returns the value of Content.
func (s *UpdateNoteRequest) GetContent() string {
	return s.Content
}

// GetContentType returns the value of ContentType.
func (s *UpdateNoteRequest) GetContentType() OptUpdateNoteRequestContentType {
	return s.ContentType
}

// GetEditCode returns the value of EditCode.
func (s *UpdateNoteRequest) GetEditCode() OptString {
	return s.EditCode
}

// GetBurnAfterReading returns the value of BurnAfterReading.
func (s *UpdateNoteRequest) GetBurnAfterReading() OptBool {
	return s.BurnAfterReading
}

// GetTTL returns the value of TTL.
func (s *UpdateNoteRequest) GetTTL() OptInt64 {
	return s.TTL
}

// GetPrivacy returns the value of Privacy.
func (s *UpdateNoteRequest) GetPrivacy() OptUpdateNoteRequestPrivacy {
	return s.Privacy
}

// SetTitle sets the value of Title.
func (s *UpdateNoteRequest) SetTitle(val OptString) {
	s.Title = val
}

// SetContent sets the value of Content.
func (s *UpdateNoteRequest) SetContent(val string) {
	s.Content = val
}

// SetContentType sets the value of ContentType.
func (s *UpdateNoteRequest) SetContentType(val OptUpdateNoteRequestContentType) {
	s.ContentType = val
}

// SetEditCode sets the value of EditCode.
func (s *UpdateNoteRequest) SetEditCode(val OptString) {
	s.EditCode = val
}

// SetBurnAfterReading sets the value of BurnAfterReading.
func (s *UpdateNoteRequest) SetBurnAfterReading(val OptBool) {
	s.BurnAfterReading = val
}

// SetTTL sets the value of TTL.
func (s *UpdateNoteRequest) SetTTL(val OptInt64) {
	s.TTL = val
}

// SetPrivacy sets the value of Privacy.
func (s *UpdateNoteRequest) SetPrivacy(val OptUpdateNoteRequestPrivacy) {
	s.Privacy = val
}

// New content type; defaults to the note's current type when omitted.
type UpdateNoteRequestContentType string

const (
	UpdateNoteRequestContentTypeTextMarkdown UpdateNoteRequestContentType = "text/markdown"
	UpdateNoteRequestContentTypeTextPlain    UpdateNoteRequestContentType = "text/plain"
)

// AllValues returns all UpdateNoteRequestContentType values.
func (UpdateNoteRequestContentType) AllValues() []UpdateNoteRequestContentType {
	return []UpdateNoteRequestContentType{
		UpdateNoteRequestContentTypeTextMarkdown,
		UpdateNoteRequestContentTypeTextPlain,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateNoteRequestContentType) MarshalText() ([]byte, error) {
	switch s {
	case UpdateNoteRequestContentTypeTextMarkdown:
		return []byte(s), nil
	case UpdateNoteRequestContentTypeTextPlain:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateNoteRequestContentType) UnmarshalText(data []byte) error {
	switch UpdateNoteRequestContentType(data) {
	case UpdateNoteRequestContentTypeTextMarkdown:
		*s = UpdateNoteRequestContentTypeTextMarkdown
		return nil
	case UpdateNoteRequestContentTypeTextPlain:
		*s = UpdateNoteRequestContentTypeTextPlain
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Update the privacy level. See `CreateNoteRequest.privacy` for the exact semantics of
// each value. Omitted keeps the note's current privacy level.
type UpdateNoteRequestPrivacy string

const (
	UpdateNoteRequestPrivacyPublic        UpdateNoteRequestPrivacy = "public"
	UpdateNoteRequestPrivacyAuthenticated UpdateNoteRequestPrivacy = "authenticated"
	UpdateNoteRequestPrivacyOwner         UpdateNoteRequestPrivacy = "owner"
)

// AllValues returns all UpdateNoteRequestPrivacy values.
func (UpdateNoteRequestPrivacy) AllValues() []UpdateNoteRequestPrivacy {
	return []UpdateNoteRequestPrivacy{
		UpdateNoteRequestPrivacyPublic,
		UpdateNoteRequestPrivacyAuthenticated,
		UpdateNoteRequestPrivacyOwner,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateNoteRequestPrivacy) MarshalText() ([]byte, error) {
	switch s {
	case UpdateNoteRequestPrivacyPublic:
		return []byte(s), nil
	case UpdateNoteRequestPrivacyAuthenticated:
		return []byte(s), nil
	case UpdateNoteRequestPrivacyOwner:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateNoteRequestPrivacy) UnmarshalText(data []byte) error {
	switch UpdateNoteRequestPrivacy(data) {
	case UpdateNoteRequestPrivacyPublic:
		*s = UpdateNoteRequestPrivacyPublic
		return nil
	case UpdateNoteRequestPrivacyAuthenticated:
		*s = UpdateNoteRequestPrivacyAuthenticated
		return nil
	case UpdateNoteRequestPrivacyOwner:
		*s = UpdateNoteRequestPrivacyOwner
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type UpdateNoteUnauthorized ErrorResponse

func (*UpdateNoteUnauthorized) updateNoteRes() {}

type UpdateNoteUnprocessableEntity ErrorResponse

func (*UpdateNoteUnprocessableEntity) updateNoteRes() {}
