// Code generated by ogen, DO NOT EDIT.

package ogenapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateNote implements createNote operation.
	//
	// Creates a note and returns it together with the one-time `edit_code`.
	// If `slug` is omitted a 10-character random slug is generated.
	// Responds `409 Conflict` when the requested slug is already taken.
	//
	// POST /notes
	CreateNote(ctx context.Context, req *CreateNoteRequest) (CreateNoteRes, error)
	// DeleteNote implements deleteNote operation.
	//
	// Permanently deletes the note.  The edit code must be supplied either as the
	// `X-Edit-Code` request header or the `edit_code` query parameter — unless the request is
	// authenticated (bearer token or session) as the exact user who created the note, in which
	// case no edit code is needed. See "Edit codes and ownership" above.
	// Prefer the `X-Edit-Code` header over the `edit_code` query parameter: a query string can
	// end up in reverse-proxy/CDN access logs or in the `Referer` header of a same-origin
	// follow-up request, while padmark's own logging never records it (see openapi.yaml's
	// `edit_code` query parameter description). The query parameter exists only for manual/curl
	// convenience — the CLI always uses the header. Better still, sign in (session or API
	// token) before creating the note and skip the edit code entirely.
	//
	// DELETE /notes/{id}
	DeleteNote(ctx context.Context, params DeleteNoteParams) (DeleteNoteRes, error)
	// GetNote implements getNote operation.
	//
	// Returns the note as JSON.  Increments the view counter on every call.
	// For burn-after-reading notes **without TTL** the note is deleted on this request and
	// the response body is the last snapshot of the note before deletion.
	// For burn-after-reading notes **with TTL** `expires_at` is set on the first read to
	// `now + ttl` and the note expires automatically when that timestamp is reached.
	//
	// GET /notes/{id}
	GetNote(ctx context.Context, params GetNoteParams) (GetNoteRes, error)
	// Healthz implements healthz operation.
	//
	// Returns 200 as long as the process is running.
	//
	// GET /healthz
	Healthz(ctx context.Context) error
	// Readyz implements readyz operation.
	//
	// Returns 200 when the storage backend is reachable, 503 otherwise.
	//
	// GET /readyz
	Readyz(ctx context.Context) (ReadyzRes, error)
	// UpdateNote implements updateNote operation.
	//
	// Replaces the note's title, content, content type, and burn settings.
	// The `edit_code` must match the one returned when the note was created — unless the
	// request is authenticated (bearer token or session) as the exact user who created the
	// note, in which case `edit_code` may be omitted. See "Edit codes and ownership" above.
	// Returns the updated note.
	//
	// PUT /notes/{id}
	UpdateNote(ctx context.Context, req *UpdateNoteRequest, params UpdateNoteParams) (UpdateNoteRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
