// Code generated by ogen, DO NOT EDIT.

package ogenapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateNote implements createNote operation.
	//
	// Creates a note and returns it together with the one-time `edit_code`.
	// If `slug` is omitted a 10-character random slug is generated.
	// Responds `409 Conflict` when the requested slug is already taken.
	//
	// POST /notes
	CreateNote(ctx context.Context, req *CreateNoteRequest) (CreateNoteRes, error)
	// DeleteNote implements deleteNote operation.
	//
	// Permanently deletes the note.  The edit code must be supplied either as the
	// `X-Edit-Code` request header or the `edit_code` query parameter.
	//
	// DELETE /notes/{id}
	DeleteNote(ctx context.Context, params DeleteNoteParams) (DeleteNoteRes, error)
	// GetNote implements getNote operation.
	//
	// Returns the note as JSON.  Increments the view counter on every call.
	// For burn-after-reading notes **without TTL** the note is deleted on this request and
	// the response body is the last snapshot of the note before deletion.
	// For burn-after-reading notes **with TTL** `expires_at` is set on the first read to
	// `now + ttl` and the note expires automatically when that timestamp is reached.
	//
	// GET /notes/{id}
	GetNote(ctx context.Context, params GetNoteParams) (GetNoteRes, error)
	// Healthz implements healthz operation.
	//
	// Returns 200 as long as the process is running.
	//
	// GET /healthz
	Healthz(ctx context.Context) error
	// Readyz implements readyz operation.
	//
	// Returns 200 when the storage backend is reachable, 503 otherwise.
	//
	// GET /readyz
	Readyz(ctx context.Context) (ReadyzRes, error)
	// UpdateNote implements updateNote operation.
	//
	// Replaces the note's title, content, content type, and burn settings.
	// The `edit_code` must match the one returned when the note was created.
	// Returns the updated note.
	//
	// PUT /notes/{id}
	UpdateNote(ctx context.Context, req *UpdateNoteRequest, params UpdateNoteParams) (UpdateNoteRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
