// Code generated by ogen, DO NOT EDIT.

package ogenapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateNote implements createNote operation.
	//
	// Create a new note.
	//
	// POST /notes
	CreateNote(ctx context.Context, req *CreateNoteRequest) (CreateNoteRes, error)
	// DeleteNote implements deleteNote operation.
	//
	// Requires the edit code via X-Edit-Code header or edit_code query parameter.
	//
	// DELETE /notes/{id}
	DeleteNote(ctx context.Context, params DeleteNoteParams) (DeleteNoteRes, error)
	// GetNote implements getNote operation.
	//
	// Returns a note as JSON. Increments the view counter.
	//
	// GET /notes/{id}
	GetNote(ctx context.Context, params GetNoteParams) (GetNoteRes, error)
	// Healthz implements healthz operation.
	//
	// Liveness probe.
	//
	// GET /healthz
	Healthz(ctx context.Context) error
	// Readyz implements readyz operation.
	//
	// Readiness probe.
	//
	// GET /readyz
	Readyz(ctx context.Context) (ReadyzRes, error)
	// UpdateNote implements updateNote operation.
	//
	// Requires the edit code that was returned when the note was created.
	//
	// PUT /notes/{id}
	UpdateNote(ctx context.Context, req *UpdateNoteRequest, params UpdateNoteParams) (UpdateNoteRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
