// Code generated by ogen, DO NOT EDIT.

package ogenapi

import (
	"time"

	"github.com/go-faster/errors"
)

type CreateNoteBadRequest ErrorResponse

func (*CreateNoteBadRequest) createNoteRes() {}

type CreateNoteConflict ErrorResponse

func (*CreateNoteConflict) createNoteRes() {}

type CreateNoteInternalServerError ErrorResponse

func (*CreateNoteInternalServerError) createNoteRes() {}

// Ref: #/components/schemas/CreateNoteRequest
type CreateNoteRequest struct {
	Title            string                          `json:"title"`
	Content          string                          `json:"content"`
	ContentType      OptCreateNoteRequestContentType `json:"content_type"`
	Slug             OptString                       `json:"slug"`
	TTL              OptInt64                        `json:"ttl"`
	BurnAfterReading OptBool                         `json:"burn_after_reading"`
}

// GetTitle returns the value of Title.
func (s *CreateNoteRequest) GetTitle() string {
	return s.Title
}

// GetContent returns the value of Content.
func (s *CreateNoteRequest) GetContent() string {
	return s.Content
}

// GetContentType returns the value of ContentType.
func (s *CreateNoteRequest) GetContentType() OptCreateNoteRequestContentType {
	return s.ContentType
}

// GetSlug returns the value of Slug.
func (s *CreateNoteRequest) GetSlug() OptString {
	return s.Slug
}

// GetTTL returns the value of TTL.
func (s *CreateNoteRequest) GetTTL() OptInt64 {
	return s.TTL
}

// GetBurnAfterReading returns the value of BurnAfterReading.
func (s *CreateNoteRequest) GetBurnAfterReading() OptBool {
	return s.BurnAfterReading
}

// SetTitle sets the value of Title.
func (s *CreateNoteRequest) SetTitle(val string) {
	s.Title = val
}

// SetContent sets the value of Content.
func (s *CreateNoteRequest) SetContent(val string) {
	s.Content = val
}

// SetContentType sets the value of ContentType.
func (s *CreateNoteRequest) SetContentType(val OptCreateNoteRequestContentType) {
	s.ContentType = val
}

// SetSlug sets the value of Slug.
func (s *CreateNoteRequest) SetSlug(val OptString) {
	s.Slug = val
}

// SetTTL sets the value of TTL.
func (s *CreateNoteRequest) SetTTL(val OptInt64) {
	s.TTL = val
}

// SetBurnAfterReading sets the value of BurnAfterReading.
func (s *CreateNoteRequest) SetBurnAfterReading(val OptBool) {
	s.BurnAfterReading = val
}

type CreateNoteRequestContentType string

const (
	CreateNoteRequestContentTypeTextMarkdown CreateNoteRequestContentType = "text/markdown"
	CreateNoteRequestContentTypeTextPlain    CreateNoteRequestContentType = "text/plain"
)

// AllValues returns all CreateNoteRequestContentType values.
func (CreateNoteRequestContentType) AllValues() []CreateNoteRequestContentType {
	return []CreateNoteRequestContentType{
		CreateNoteRequestContentTypeTextMarkdown,
		CreateNoteRequestContentTypeTextPlain,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateNoteRequestContentType) MarshalText() ([]byte, error) {
	switch s {
	case CreateNoteRequestContentTypeTextMarkdown:
		return []byte(s), nil
	case CreateNoteRequestContentTypeTextPlain:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateNoteRequestContentType) UnmarshalText(data []byte) error {
	switch CreateNoteRequestContentType(data) {
	case CreateNoteRequestContentTypeTextMarkdown:
		*s = CreateNoteRequestContentTypeTextMarkdown
		return nil
	case CreateNoteRequestContentTypeTextPlain:
		*s = CreateNoteRequestContentTypeTextPlain
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateNoteRequestEntityTooLarge ErrorResponse

func (*CreateNoteRequestEntityTooLarge) createNoteRes() {}

// Ref: #/components/schemas/CreateNoteResponse
type CreateNoteResponse struct {
	ID               string                        `json:"id"`
	Title            string                        `json:"title"`
	Content          string                        `json:"content"`
	ContentType      CreateNoteResponseContentType `json:"content_type"`
	Views            int                           `json:"views"`
	BurnAfterReading bool                          `json:"burn_after_reading"`
	CreatedAt        time.Time                     `json:"created_at"`
	UpdatedAt        time.Time                     `json:"updated_at"`
	ExpiresAt        OptDateTime                   `json:"expires_at"`
	EditCode         string                        `json:"edit_code"`
}

// GetID returns the value of ID.
func (s *CreateNoteResponse) GetID() string {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *CreateNoteResponse) GetTitle() string {
	return s.Title
}

// GetContent returns the value of Content.
func (s *CreateNoteResponse) GetContent() string {
	return s.Content
}

// GetContentType returns the value of ContentType.
func (s *CreateNoteResponse) GetContentType() CreateNoteResponseContentType {
	return s.ContentType
}

// GetViews returns the value of Views.
func (s *CreateNoteResponse) GetViews() int {
	return s.Views
}

// GetBurnAfterReading returns the value of BurnAfterReading.
func (s *CreateNoteResponse) GetBurnAfterReading() bool {
	return s.BurnAfterReading
}

// GetCreatedAt returns the value of CreatedAt.
func (s *CreateNoteResponse) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *CreateNoteResponse) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *CreateNoteResponse) GetExpiresAt() OptDateTime {
	return s.ExpiresAt
}

// GetEditCode returns the value of EditCode.
func (s *CreateNoteResponse) GetEditCode() string {
	return s.EditCode
}

// SetID sets the value of ID.
func (s *CreateNoteResponse) SetID(val string) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *CreateNoteResponse) SetTitle(val string) {
	s.Title = val
}

// SetContent sets the value of Content.
func (s *CreateNoteResponse) SetContent(val string) {
	s.Content = val
}

// SetContentType sets the value of ContentType.
func (s *CreateNoteResponse) SetContentType(val CreateNoteResponseContentType) {
	s.ContentType = val
}

// SetViews sets the value of Views.
func (s *CreateNoteResponse) SetViews(val int) {
	s.Views = val
}

// SetBurnAfterReading sets the value of BurnAfterReading.
func (s *CreateNoteResponse) SetBurnAfterReading(val bool) {
	s.BurnAfterReading = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *CreateNoteResponse) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *CreateNoteResponse) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *CreateNoteResponse) SetExpiresAt(val OptDateTime) {
	s.ExpiresAt = val
}

// SetEditCode sets the value of EditCode.
func (s *CreateNoteResponse) SetEditCode(val string) {
	s.EditCode = val
}

type CreateNoteResponseContentType string

const (
	CreateNoteResponseContentTypeTextMarkdown CreateNoteResponseContentType = "text/markdown"
	CreateNoteResponseContentTypeTextPlain    CreateNoteResponseContentType = "text/plain"
)

// AllValues returns all CreateNoteResponseContentType values.
func (CreateNoteResponseContentType) AllValues() []CreateNoteResponseContentType {
	return []CreateNoteResponseContentType{
		CreateNoteResponseContentTypeTextMarkdown,
		CreateNoteResponseContentTypeTextPlain,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateNoteResponseContentType) MarshalText() ([]byte, error) {
	switch s {
	case CreateNoteResponseContentTypeTextMarkdown:
		return []byte(s), nil
	case CreateNoteResponseContentTypeTextPlain:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateNoteResponseContentType) UnmarshalText(data []byte) error {
	switch CreateNoteResponseContentType(data) {
	case CreateNoteResponseContentTypeTextMarkdown:
		*s = CreateNoteResponseContentTypeTextMarkdown
		return nil
	case CreateNoteResponseContentTypeTextPlain:
		*s = CreateNoteResponseContentTypeTextPlain
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// CreateNoteResponseHeaders wraps CreateNoteResponse with response headers.
type CreateNoteResponseHeaders struct {
	Location OptString
	Response CreateNoteResponse
}

// GetLocation returns the value of Location.
func (s *CreateNoteResponseHeaders) GetLocation() OptString {
	return s.Location
}

// GetResponse returns the value of Response.
func (s *CreateNoteResponseHeaders) GetResponse() CreateNoteResponse {
	return s.Response
}

// SetLocation sets the value of Location.
func (s *CreateNoteResponseHeaders) SetLocation(val OptString) {
	s.Location = val
}

// SetResponse sets the value of Response.
func (s *CreateNoteResponseHeaders) SetResponse(val CreateNoteResponse) {
	s.Response = val
}

func (*CreateNoteResponseHeaders) createNoteRes() {}

type CreateNoteUnauthorized ErrorResponse

func (*CreateNoteUnauthorized) createNoteRes() {}

type CreateNoteUnprocessableEntity ErrorResponse

func (*CreateNoteUnprocessableEntity) createNoteRes() {}

type DeleteNoteForbidden ErrorResponse

func (*DeleteNoteForbidden) deleteNoteRes() {}

type DeleteNoteInternalServerError ErrorResponse

func (*DeleteNoteInternalServerError) deleteNoteRes() {}

// DeleteNoteNoContent is response for DeleteNote operation.
type DeleteNoteNoContent struct{}

func (*DeleteNoteNoContent) deleteNoteRes() {}

type DeleteNoteNotFound ErrorResponse

func (*DeleteNoteNotFound) deleteNoteRes() {}

type DeleteNoteUnauthorized ErrorResponse

func (*DeleteNoteUnauthorized) deleteNoteRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

func (*ErrorResponse) readyzRes() {}

type GetNoteGone ErrorResponse

func (*GetNoteGone) getNoteRes() {}

type GetNoteInternalServerError ErrorResponse

func (*GetNoteInternalServerError) getNoteRes() {}

type GetNoteNotFound ErrorResponse

func (*GetNoteNotFound) getNoteRes() {}

// HealthzOK is response for Healthz operation.
type HealthzOK struct{}

// Ref: #/components/schemas/NoteResponse
type NoteResponse struct {
	ID               string                  `json:"id"`
	Title            string                  `json:"title"`
	Content          string                  `json:"content"`
	ContentType      NoteResponseContentType `json:"content_type"`
	Views            int                     `json:"views"`
	BurnAfterReading bool                    `json:"burn_after_reading"`
	CreatedAt        time.Time               `json:"created_at"`
	UpdatedAt        time.Time               `json:"updated_at"`
	ExpiresAt        OptDateTime             `json:"expires_at"`
}

// GetID returns the value of ID.
func (s *NoteResponse) GetID() string {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *NoteResponse) GetTitle() string {
	return s.Title
}

// GetContent returns the value of Content.
func (s *NoteResponse) GetContent() string {
	return s.Content
}

// GetContentType returns the value of ContentType.
func (s *NoteResponse) GetContentType() NoteResponseContentType {
	return s.ContentType
}

// GetViews returns the value of Views.
func (s *NoteResponse) GetViews() int {
	return s.Views
}

// GetBurnAfterReading returns the value of BurnAfterReading.
func (s *NoteResponse) GetBurnAfterReading() bool {
	return s.BurnAfterReading
}

// GetCreatedAt returns the value of CreatedAt.
func (s *NoteResponse) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *NoteResponse) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *NoteResponse) GetExpiresAt() OptDateTime {
	return s.ExpiresAt
}

// SetID sets the value of ID.
func (s *NoteResponse) SetID(val string) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *NoteResponse) SetTitle(val string) {
	s.Title = val
}

// SetContent sets the value of Content.
func (s *NoteResponse) SetContent(val string) {
	s.Content = val
}

// SetContentType sets the value of ContentType.
func (s *NoteResponse) SetContentType(val NoteResponseContentType) {
	s.ContentType = val
}

// SetViews sets the value of Views.
func (s *NoteResponse) SetViews(val int) {
	s.Views = val
}

// SetBurnAfterReading sets the value of BurnAfterReading.
func (s *NoteResponse) SetBurnAfterReading(val bool) {
	s.BurnAfterReading = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *NoteResponse) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *NoteResponse) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *NoteResponse) SetExpiresAt(val OptDateTime) {
	s.ExpiresAt = val
}

func (*NoteResponse) getNoteRes()    {}
func (*NoteResponse) updateNoteRes() {}

type NoteResponseContentType string

const (
	NoteResponseContentTypeTextMarkdown NoteResponseContentType = "text/markdown"
	NoteResponseContentTypeTextPlain    NoteResponseContentType = "text/plain"
)

// AllValues returns all NoteResponseContentType values.
func (NoteResponseContentType) AllValues() []NoteResponseContentType {
	return []NoteResponseContentType{
		NoteResponseContentTypeTextMarkdown,
		NoteResponseContentTypeTextPlain,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s NoteResponseContentType) MarshalText() ([]byte, error) {
	switch s {
	case NoteResponseContentTypeTextMarkdown:
		return []byte(s), nil
	case NoteResponseContentTypeTextPlain:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *NoteResponseContentType) UnmarshalText(data []byte) error {
	switch NoteResponseContentType(data) {
	case NoteResponseContentTypeTextMarkdown:
		*s = NoteResponseContentTypeTextMarkdown
		return nil
	case NoteResponseContentTypeTextPlain:
		*s = NoteResponseContentTypeTextPlain
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCreateNoteRequestContentType returns new OptCreateNoteRequestContentType with value set to v.
func NewOptCreateNoteRequestContentType(v CreateNoteRequestContentType) OptCreateNoteRequestContentType {
	return OptCreateNoteRequestContentType{
		Value: v,
		Set:   true,
	}
}

// OptCreateNoteRequestContentType is optional CreateNoteRequestContentType.
type OptCreateNoteRequestContentType struct {
	Value CreateNoteRequestContentType
	Set   bool
}

// IsSet returns true if OptCreateNoteRequestContentType was set.
func (o OptCreateNoteRequestContentType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCreateNoteRequestContentType) Reset() {
	var v CreateNoteRequestContentType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCreateNoteRequestContentType) SetTo(v CreateNoteRequestContentType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCreateNoteRequestContentType) Get() (v CreateNoteRequestContentType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCreateNoteRequestContentType) Or(d CreateNoteRequestContentType) CreateNoteRequestContentType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUpdateNoteRequestContentType returns new OptUpdateNoteRequestContentType with value set to v.
func NewOptUpdateNoteRequestContentType(v UpdateNoteRequestContentType) OptUpdateNoteRequestContentType {
	return OptUpdateNoteRequestContentType{
		Value: v,
		Set:   true,
	}
}

// OptUpdateNoteRequestContentType is optional UpdateNoteRequestContentType.
type OptUpdateNoteRequestContentType struct {
	Value UpdateNoteRequestContentType
	Set   bool
}

// IsSet returns true if OptUpdateNoteRequestContentType was set.
func (o OptUpdateNoteRequestContentType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUpdateNoteRequestContentType) Reset() {
	var v UpdateNoteRequestContentType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUpdateNoteRequestContentType) SetTo(v UpdateNoteRequestContentType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUpdateNoteRequestContentType) Get() (v UpdateNoteRequestContentType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUpdateNoteRequestContentType) Or(d UpdateNoteRequestContentType) UpdateNoteRequestContentType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// ReadyzOK is response for Readyz operation.
type ReadyzOK struct{}

func (*ReadyzOK) readyzRes() {}

type UpdateNoteBadRequest ErrorResponse

func (*UpdateNoteBadRequest) updateNoteRes() {}

type UpdateNoteForbidden ErrorResponse

func (*UpdateNoteForbidden) updateNoteRes() {}

type UpdateNoteInternalServerError ErrorResponse

func (*UpdateNoteInternalServerError) updateNoteRes() {}

type UpdateNoteNotFound ErrorResponse

func (*UpdateNoteNotFound) updateNoteRes() {}

// Ref: #/components/schemas/UpdateNoteRequest
type UpdateNoteRequest struct {
	Title            string                          `json:"title"`
	Content          string                          `json:"content"`
	ContentType      OptUpdateNoteRequestContentType `json:"content_type"`
	EditCode         string                          `json:"edit_code"`
	TTL              OptInt64                        `json:"ttl"`
	BurnAfterReading OptBool                         `json:"burn_after_reading"`
}

// GetTitle returns the value of Title.
func (s *UpdateNoteRequest) GetTitle() string {
	return s.Title
}

// GetContent returns the value of Content.
func (s *UpdateNoteRequest) GetContent() string {
	return s.Content
}

// GetContentType returns the value of ContentType.
func (s *UpdateNoteRequest) GetContentType() OptUpdateNoteRequestContentType {
	return s.ContentType
}

// GetEditCode returns the value of EditCode.
func (s *UpdateNoteRequest) GetEditCode() string {
	return s.EditCode
}

// GetTTL returns the value of TTL.
func (s *UpdateNoteRequest) GetTTL() OptInt64 {
	return s.TTL
}

// GetBurnAfterReading returns the value of BurnAfterReading.
func (s *UpdateNoteRequest) GetBurnAfterReading() OptBool {
	return s.BurnAfterReading
}

// SetTitle sets the value of Title.
func (s *UpdateNoteRequest) SetTitle(val string) {
	s.Title = val
}

// SetContent sets the value of Content.
func (s *UpdateNoteRequest) SetContent(val string) {
	s.Content = val
}

// SetContentType sets the value of ContentType.
func (s *UpdateNoteRequest) SetContentType(val OptUpdateNoteRequestContentType) {
	s.ContentType = val
}

// SetEditCode sets the value of EditCode.
func (s *UpdateNoteRequest) SetEditCode(val string) {
	s.EditCode = val
}

// SetTTL sets the value of TTL.
func (s *UpdateNoteRequest) SetTTL(val OptInt64) {
	s.TTL = val
}

// SetBurnAfterReading sets the value of BurnAfterReading.
func (s *UpdateNoteRequest) SetBurnAfterReading(val OptBool) {
	s.BurnAfterReading = val
}

type UpdateNoteRequestContentType string

const (
	UpdateNoteRequestContentTypeTextMarkdown UpdateNoteRequestContentType = "text/markdown"
	UpdateNoteRequestContentTypeTextPlain    UpdateNoteRequestContentType = "text/plain"
)

// AllValues returns all UpdateNoteRequestContentType values.
func (UpdateNoteRequestContentType) AllValues() []UpdateNoteRequestContentType {
	return []UpdateNoteRequestContentType{
		UpdateNoteRequestContentTypeTextMarkdown,
		UpdateNoteRequestContentTypeTextPlain,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateNoteRequestContentType) MarshalText() ([]byte, error) {
	switch s {
	case UpdateNoteRequestContentTypeTextMarkdown:
		return []byte(s), nil
	case UpdateNoteRequestContentTypeTextPlain:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateNoteRequestContentType) UnmarshalText(data []byte) error {
	switch UpdateNoteRequestContentType(data) {
	case UpdateNoteRequestContentTypeTextMarkdown:
		*s = UpdateNoteRequestContentTypeTextMarkdown
		return nil
	case UpdateNoteRequestContentTypeTextPlain:
		*s = UpdateNoteRequestContentTypeTextPlain
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type UpdateNoteUnauthorized ErrorResponse

func (*UpdateNoteUnauthorized) updateNoteRes() {}

type UpdateNoteUnprocessableEntity ErrorResponse

func (*UpdateNoteUnprocessableEntity) updateNoteRes() {}
