package domain

import (
	"time"
	"unicode"
)

const minPasswordLen = 12

// ValidatePassword checks complexity: min 12 chars, 1 upper, 1 lower, 1 digit, 1 special.
func ValidatePassword(password string) error {
	if len(password) < minPasswordLen {
		return ErrWeakPassword
	}

	var hasUpper, hasLower, hasDigit, hasSpecial bool

	for _, char := range password {
		switch {
		case unicode.IsUpper(char):
			hasUpper = true
		case unicode.IsLower(char):
			hasLower = true
		case unicode.IsDigit(char):
			hasDigit = true
		case unicode.IsPunct(char) || unicode.IsSymbol(char):
			hasSpecial = true
		}
	}

	if !hasUpper || !hasLower || !hasDigit || !hasSpecial {
		return ErrWeakPassword
	}

	return nil
}

// User is a registered padmark user with TOTP-based authentication.
type User struct {
	CreatedAt    time.Time
	LastLoginAt  *time.Time
	ID           string
	Username     string
	TOTPSecret   string
	PasswordHash string
	KDFSalt      []byte
	IsAdmin      bool
}

// Invite is a single-use registration link generated by an admin.
type Invite struct {
	Token     string
	CreatedBy string // User.ID
	ExpiresAt time.Time
	UsedAt    *time.Time
	UsedBy    string
}

// Session is an authenticated browser session.
type Session struct {
	SessionID string
	UserID    string
	CreatedAt time.Time
	ExpiresAt time.Time
	UserAgent string
	IP        string
}
