// Code generated by ogen, DO NOT EDIT.

package client

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteNoteParams is parameters of deleteNote operation.
type DeleteNoteParams struct {
	// Note ID (slug) — 10-char random string or the custom slug chosen at creation.
	ID string
	// Edit code returned at note creation (alternative to `edit_code` query param).
	XEditCode OptString `json:",omitempty,omitzero"`
	// Edit code returned at note creation (alternative to `X-Edit-Code` header).
	EditCode OptString `json:",omitempty,omitzero"`
}

func unpackDeleteNoteParams(packed middleware.Parameters) (params DeleteNoteParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "X-Edit-Code",
			In:   "header",
		}
		if v, ok := packed[key]; ok {
			params.XEditCode = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "edit_code",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.EditCode = v.(OptString)
		}
	}
	return params
}

func decodeDeleteNoteParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteNoteParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	h := uri.NewHeaderDecoder(r.Header)
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode header: X-Edit-Code.
	if err := func() error {
		cfg := uri.HeaderParameterDecodingConfig{
			Name:    "X-Edit-Code",
			Explode: false,
		}
		if err := h.HasParam(cfg); err == nil {
			if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotXEditCodeVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotXEditCodeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.XEditCode.SetTo(paramsDotXEditCodeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "X-Edit-Code",
			In:   "header",
			Err:  err,
		}
	}
	// Decode query: edit_code.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "edit_code",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotEditCodeVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotEditCodeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.EditCode.SetTo(paramsDotEditCodeVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "edit_code",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetNoteParams is parameters of getNote operation.
type GetNoteParams struct {
	// Note ID (slug) — 10-char random string or the custom slug chosen at creation.
	ID string
}

func unpackGetNoteParams(packed middleware.Parameters) (params GetNoteParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeGetNoteParams(args [1]string, argsEscaped bool, r *http.Request) (params GetNoteParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateNoteParams is parameters of updateNote operation.
type UpdateNoteParams struct {
	// Note ID (slug) — 10-char random string or the custom slug chosen at creation.
	ID string
}

func unpackUpdateNoteParams(packed middleware.Parameters) (params UpdateNoteParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	return params
}

func decodeUpdateNoteParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateNoteParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
