// Code generated by ogen, DO NOT EDIT.

package client

// setDefaults set default value of fields.
func (s *CreateNoteRequest) setDefaults() {
	{
		val := CreateNoteRequestContentType("text/markdown")
		s.ContentType.SetTo(val)
	}
	{
		val := bool(false)
		s.BurnAfterReading.SetTo(val)
	}
}
