// Code generated by ogen, DO NOT EDIT.
package client

type CreateNoteRes interface {
	createNoteRes()
}

type DeleteNoteRes interface {
	deleteNoteRes()
}

type GetNoteRes interface {
	getNoteRes()
}

type ReadyzRes interface {
	readyzRes()
}

type UpdateNoteRes interface {
	updateNoteRes()
}
