// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateNote implements createNote operation.
//
// Create a new note.
//
// POST /notes
func (UnimplementedHandler) CreateNote(ctx context.Context, req *CreateNoteRequest) (r CreateNoteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteNote implements deleteNote operation.
//
// Requires the edit code via X-Edit-Code header or edit_code query parameter.
//
// DELETE /notes/{id}
func (UnimplementedHandler) DeleteNote(ctx context.Context, params DeleteNoteParams) (r DeleteNoteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNote implements getNote operation.
//
// Returns a note as JSON. Increments the view counter.
//
// GET /notes/{id}
func (UnimplementedHandler) GetNote(ctx context.Context, params GetNoteParams) (r GetNoteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Healthz implements healthz operation.
//
// Liveness probe.
//
// GET /healthz
func (UnimplementedHandler) Healthz(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// Readyz implements readyz operation.
//
// Readiness probe.
//
// GET /readyz
func (UnimplementedHandler) Readyz(ctx context.Context) (r ReadyzRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateNote implements updateNote operation.
//
// Requires the edit code that was returned when the note was created.
//
// PUT /notes/{id}
func (UnimplementedHandler) UpdateNote(ctx context.Context, req *UpdateNoteRequest, params UpdateNoteParams) (r UpdateNoteRes, _ error) {
	return r, ht.ErrNotImplemented
}
